### ISSUE TITLE
Getting a BlockState requires BlockInput which isn't part of fabric

### ISSUE THREAD

**Issue by Chase22** [henkelmax/admiral#1]
**Bug description**
More of a question than a bug report, but according to the supported argument types to get a BlockStateArgument i'm supposed to supply a BlockInput as argument type. I'm using fabric and as far as my research found out this is a forge class. Am i missing something or how can i get a block id as a command input?

**Versions**
- fabric 0.15.5
- 1.20.4
- 0.4.4+1.20.4+fabric

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This class is neither part of Forge nor Fabric. Its Minecraft: `net.minecraft.commands.arguments.blocks.BlockInput`.
All examples are with official mappings. You might be using other mappings so it would be named differently for you.
