### ISSUE TITLE
Not possible to add Argument Suggestions

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [henkelmax/admiral#2]
### Bug description

Can't get argument suggestions to work since there's no way to add them server-side only

### Minecraft version

1.21.1

### Mod version

0.4.5-1.21.1

### Mod loader and version

Fabric Loader 0.16.2

### Steps to reproduce

1) Add custom command
2) Add string argument
3) Try to add suggestions
4) Receive error since you cant add types server-side only

### Log files

There's basically no logs

**Comment by henkelmax** [comment]
https://github.com/henkelmax/admiral/blob/2669585599c221b41ed3facf5de454b56ef6c4f9/core/src/main/java/de/maxhenkel/admiral/argumenttype/ArgumentTypeSupplier.java#L27

**Comment by MrMasrozYTLIVE** [comment]
> https://github.com/henkelmax/admiral/blob/2669585599c221b41ed3facf5de454b56ef6c4f9/core/src/main/java/de/maxhenkel/admiral/argumenttype/ArgumentTypeSupplier.java#L27

Is there any example on how to use it?

**Comment by MrMasrozYTLIVE** [comment]
> > https://github.com/henkelmax/admiral/blob/2669585599c221b41ed3facf5de454b56ef6c4f9/core/src/main/java/de/maxhenkel/admiral/argumenttype/ArgumentTypeSupplier.java#L27
> 
> Is there any example on how to use it?

Whenever I try to use this thing I get ` java.lang.IllegalArgumentException: Unrecognized argument type net.mitask.happyworldlore.command.CommandHandler$1$$Lambda/0x000001be9bd1f9a0@5ba542f0 (class net.mitask.happyworldlore.command.CommandHandler$1$$Lambda/0x000001be9bd1f9a0)`

![image](https://github.com/user-attachments/assets/6d9770fd-f45d-4a41-8f34-bc6607b82b74)
![image](https://github.com/user-attachments/assets/bdc69678-5b4d-4437-88f8-4d74bbc84b52)
(It doesn't matter if Variable implements ArgumentType or no, there's no difference)

**Comment by MrMasrozYTLIVE** [comment]
@henkelmax hi?
